#!/bin/bash
#
# ffid.sh — manage isolated Camoufox identity profiles
#
#   ./ffid.sh setup     one-time: python venv + camoufox install (same as: python3 install.py)
#   ./ffid.sh update    upgrade camoufox (python package + browser) to the latest release
#   ./ffid.sh dashboard start the web dashboard at http://127.0.0.1:8787
#   ./ffid.sh create    create fresh profiles with per-profile config + personas
#   ./ffid.sh launch [url]  open one window per profile (each via its own SOCKS5 exit),
#                           optionally loading the given URL (default: about:blank)
#   ./ffid.sh stop      kill all identity instances and DELETE the profiles
#   ./ffid.sh status    show which identity instances are running
#
# Number of identities is set by FFID_SESSIONS (default 10, max 100), e.g.
#   FFID_SESSIONS=4 ./ffid.sh create && ./ffid.sh launch
# launch always opens whatever profiles exist, so it needs no count itself.
#
# Profiles are disposable: stop wipes them entirely, and create rebuilds from
# scratch — so every session starts from genuinely fresh state and nothing
# (cookies, history, cache, logins) survives between sessions.
#
# Proxies are read from proxies.conf (one "host:port" per line, or "DIRECT"),
# cycled modulo the entry count if FFID_SESSIONS exceeds it (shared egress
# links those identities — a warning is printed). create sends a GeoIP lookup
# through each proxy so every identity's timezone, locale and geolocation
# match its exit IP — the proxies must be UP during create. Fingerprints
# (OS, fonts, WebGL, screen, etc.) are generated by Camoufox's BrowserForge
# engine and are different for every identity.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILES_DIR="$ROOT/profiles"
CONF="$ROOT/proxies.conf"
# browser installed by 'setup' via the camoufox package manager
FF="${FIREFOX_BIN:-$(ls -d "$HOME"/Library/Caches/camoufox/browsers/official/*/Camoufox.app/Contents/MacOS/camoufox 2>/dev/null | head -1)}"
N="${FFID_SESSIONS:-10}"
[[ "$N" =~ ^[1-9][0-9]*$ ]] || { echo "error: FFID_SESSIONS must be a positive integer (got '$N')" >&2; exit 1; }
(( N <= 100 )) || { echo "error: FFID_SESSIONS is capped at 100 (got $N)" >&2; exit 1; }

# Seconds of random stagger between launches (avoids synchronized first connections).
LAUNCH_STAGGER=5

# ---------------------------------------------------------------------------

proxy_count() {
  grep -v '^\s*#' "$CONF" | grep -v '^\s*$' | wc -l | tr -d ' '
}

proxy_for() {  # $1 = 1-based index -> prints "host port" or "DIRECT" (cycled modulo entry count)
  local count idx line
  count=$(proxy_count)
  if (( count == 0 )); then
    echo "MISSING"
    return
  fi
  idx=$(( ($1 - 1) % count + 1 ))
  line=$(grep -v '^\s*#' "$CONF" | grep -v '^\s*$' | sed -n "${idx}p")
  if [[ -z "$line" ]]; then
    echo "MISSING"
  elif [[ "$line" == "DIRECT" ]]; then
    echo "DIRECT"
  else
    echo "${line%:*} ${line##*:}"
  fi
}

write_user_js() {  # $1 = profile dir, $2 = 0-based index
  local dir="$1" i="$2"
  local p host port
  p=$(proxy_for $((i + 1)))

  {
    echo "// identity $((i + 1)) — generated by ffid.sh, edit via the script"
    echo

    if [[ "$p" == "DIRECT" || "$p" == "MISSING" ]]; then
      echo "user_pref(\"network.proxy.type\", 0); // WARNING: direct connection, no proxy"
    else
      host="${p% *}"; port="${p##* }"
      echo "user_pref(\"network.proxy.type\", 1);"
      echo "user_pref(\"network.proxy.socks\", \"$host\");"
      echo "user_pref(\"network.proxy.socks_port\", $port);"
      echo "user_pref(\"network.proxy.socks_version\", 5);"
      echo "user_pref(\"network.proxy.socks_remote_dns\", true);"
      echo "user_pref(\"network.proxy.failover_direct\", false); // never leak direct if proxy dies"
    fi
    echo "user_pref(\"network.dns.disableIPv6\", true); // prevent IPv6 bypassing the proxy"
    echo
    echo "// WebRTC: hard off + belt-and-suspenders"
    echo "user_pref(\"media.peerconnection.enabled\", false);"
    echo "user_pref(\"media.peerconnection.ice.default_address_only\", true);"
    echo "user_pref(\"media.peerconnection.ice.no_host\", true);"
    echo "user_pref(\"media.peerconnection.ice.proxy_only_if_behind_proxy\", true);"
    echo
    echo "// NOTE: no privacy.resistFingerprinting here — Camoufox does its own"
    echo "// C++-level spoofing via the persona config; RFP would conflict with it."
    echo
    echo "// hygiene"
    echo "user_pref(\"browser.shell.checkDefaultBrowser\", false);"
    echo "user_pref(\"browser.shell.skipDefaultBrowserCheckOnFirstRun\", true);"
    echo "user_pref(\"browser.aboutwelcome.enabled\", false);"
    echo "user_pref(\"trailhead.firstrun.didSeeAboutWelcome\", true);"
    echo "user_pref(\"datareporting.policy.dataSubmissionEnabled\", false);"
    echo "user_pref(\"datareporting.healthreport.uploadEnabled\", false);"
    echo "user_pref(\"app.shield.optoutstudies.enabled\", false);"
    echo "user_pref(\"browser.discovery.enabled\", false);"
    echo "user_pref(\"browser.crashReports.unsubmittedCheck.autoSubmit2\", false);"
    echo "user_pref(\"signon.rememberSignons\", false);"
    echo "user_pref(\"signon.autofillForms\", false);"
    echo "user_pref(\"browser.formfill.enable\", false);"
    echo "user_pref(\"browser.sessionstore.resume_from_crash\", false);"
    echo "user_pref(\"toolkit.startup.max_resumed_crashes\", -1); // never offer Troubleshoot Mode after a hard kill"
    echo "user_pref(\"browser.sessionstore.max_resumed_crashes\", -1); // legacy name of the same pref"
    echo "user_pref(\"dom.security.https_only_mode\", true);"
  } > "$dir/user.js"
}

cmd_create() {
  [[ -f "$CONF" ]] || { echo "error: $CONF not found"; exit 1; }
  [[ -x "$ROOT/.venv/bin/python" ]] || { echo "error: .venv missing — run '$0 setup' first" >&2; exit 1; }
  local count
  count=$(proxy_count)
  (( count > 0 )) || { echo "error: $CONF has no proxy entries" >&2; exit 1; }
  (( N > count )) && echo "warning: $count proxies for $N identities — egresses repeat (shared IPs link identities)" >&2
  # non-blocking freshness check — warns if camoufox is behind the latest release
  PYTHONPATH="$ROOT" "$ROOT/.venv/bin/python" -c "import ffid_core; ffid_core.log_camoufox_freshness()" \
    || echo "warning: camoufox update check failed (offline?)" >&2
  # clear any previous set so a smaller N doesn't leave stale profiles behind
  if [[ -d "$PROFILES_DIR" && "$PROFILES_DIR" == "$ROOT/profiles" ]]; then
    rm -rf "$PROFILES_DIR"
  fi
  mkdir -p "$PROFILES_DIR"
  local i dir p
  for ((i = 0; i < N; i++)); do
    dir="$PROFILES_DIR/id$((i + 1))"
    p=$(proxy_for $((i + 1)))
    [[ "$p" == "DIRECT" ]] && echo "warning: id$((i + 1)) will connect DIRECTLY (your real IP)" >&2
    mkdir -p "$dir"
    write_user_js "$dir" "$i"
  done
  # generate one Camoufox persona per identity (does GeoIP lookups through the proxies)
  "$ROOT/.venv/bin/python" "$ROOT/gen_personas.py" "$N"
  echo
  echo "Done. Launch with: $0 launch"
}

cmd_launch() {
  [[ -x "$FF" ]] || { echo "error: Camoufox not found at $FF (set FIREFOX_BIN to override)"; exit 1; }
  local url="${1:-about:blank}"
  local i dir launched=0
  # open whatever profiles exist (consecutive id1..idN), regardless of FFID_SESSIONS
  for ((i = 1; ; i++)); do
    dir="$PROFILES_DIR/id$i"
    [[ -d "$dir" ]] || break
    [[ -f "$dir/user.js" && -f "$dir/persona.env" ]] || { echo "error: $dir is incomplete — run '$0 create' first"; exit 1; }
    if (( LAUNCH_STAGGER > 0 )); then
      sleep $((RANDOM % (LAUNCH_STAGGER + 1)))
    fi
    (
      set -a; source "$dir/persona.env"; set +a
      exec "$FF" -no-remote -profile "$dir" --new-window "$url" >/dev/null 2>&1
    ) &
    echo "launched id$i (pid $!)"
    ((launched++)) || true
  done
  (( launched > 0 )) || { echo "error: no profiles found — run '$0 create' first"; exit 1; }
  echo
  echo "All $launched identities running. Verify each one before use:"
  echo "  - IP check:        https://browserleaks.com/ip"
  echo "  - WebRTC/DNS leak: https://browserleaks.com/webrtc"
  echo "  - fingerprint:     https://coveryourtracks.eff.org"
}

cmd_setup() {
  command -v python3 >/dev/null || { echo "error: python3 not found — install Python 3.10+ first" >&2; exit 1; }
  python3 "$ROOT/install.py"
}

cmd_dashboard() {
  [[ -x "$ROOT/.venv/bin/python" ]] || { echo "error: .venv missing — run '$0 setup' first" >&2; exit 1; }
  exec "$ROOT/.venv/bin/python" "$ROOT/dashboard.py"
}

cmd_update() {
  [[ -x "$ROOT/.venv/bin/python" ]] || { echo "error: .venv missing — run '$0 setup' first" >&2; exit 1; }
  PYTHONPATH="$ROOT" "$ROOT/.venv/bin/python" -c "import ffid_core; ffid_core.update_camoufox()"
}

cmd_stop() {
  pkill -f "$PROFILES_DIR/id" && echo "instances killed" || echo "no instances running"
  # wait for Firefox to flush and exit before deleting (large session counts
  # need a while; an unclean exit trips the Troubleshoot Mode prompt next launch)
  local tries=0
  while pgrep -f "$PROFILES_DIR/id" >/dev/null && (( tries++ < 120 )); do
    sleep 0.5
  done
  if pgrep -f "$PROFILES_DIR/id" >/dev/null; then
    pkill -9 -f "$PROFILES_DIR/id" || true
    sleep 1
  fi
  # safety: only ever delete the profiles dir inside this script's folder
  if [[ -d "$PROFILES_DIR" && "$PROFILES_DIR" == "$ROOT/profiles" ]]; then
    rm -rf "$PROFILES_DIR"
    echo "profiles deleted — run '$0 create' to start a fresh set"
  fi
}

cmd_status() {
  pgrep -fl "$PROFILES_DIR/id" || echo "no identity instances running"
}

case "${1:-}" in
  setup)     cmd_setup ;;
  update)    cmd_update ;;
  dashboard) cmd_dashboard ;;
  create)    cmd_create ;;
  launch)    cmd_launch "${2:-}" ;;
  stop)      cmd_stop ;;
  status)    cmd_status ;;
  *) echo "usage: $0 {setup|update|dashboard|create|launch [url]|stop|status}"; exit 1 ;;
esac
