"""
Cross-platform core for managing isolated Camoufox identity profiles.

This is the Python-native equivalent of ffid.sh (which stays macOS/Linux-only):
create/launch/stop/status, usable from the dashboard or any other Python
driver. Browser discovery goes through the camoufox package, so it works on
macOS, Windows and Linux.

Instances launched here are tracked as Popen handles, so stop/status work
without pgrep/pkill. Instances launched externally (via ffid.sh) are visible
on disk but show as untracked.
"""

import json
import os
import random
import re
import shlex
import shutil
import subprocess
import time
from pathlib import Path

from gen_personas import generate_personas, proxy_entries

ROOT = Path(__file__).resolve().parent
CONF = ROOT / "proxies.conf"
PROFILES = ROOT / "profiles"
MAX_SESSIONS = 100

# Seconds of random stagger between launches (avoids synchronized first connections).
LAUNCH_STAGGER = 5

# ident -> {"popen": Popen, "url": str, "started_at": float}
_tracked = {}


def proxy_for(index, entries=None):
    """1-based identity index -> proxies.conf entry, cycled modulo entry count."""
    entries = proxy_entries() if entries is None else entries
    if not entries:
        raise RuntimeError(f"{CONF} has no proxy entries")
    return entries[(index - 1) % len(entries)]


def browser_path():
    override = os.environ.get("FIREFOX_BIN")
    if override:
        return override
    from camoufox.pkgman import launch_path

    return launch_path()


def write_user_js(profile_dir, index, entry):
    """index is 0-based; entry is a proxies.conf line ('host:port' or 'DIRECT')."""
    lines = [f"// identity {index + 1} — generated by ffid.sh, edit via the script", ""]
    if entry == "DIRECT":
        lines.append('user_pref("network.proxy.type", 0); // WARNING: direct connection, no proxy')
    else:
        host, _, port = entry.rpartition(":")
        lines += [
            'user_pref("network.proxy.type", 1);',
            f'user_pref("network.proxy.socks", "{host}");',
            f'user_pref("network.proxy.socks_port", {port});',
            'user_pref("network.proxy.socks_version", 5);',
            'user_pref("network.proxy.socks_remote_dns", true);',
            'user_pref("network.proxy.failover_direct", false); // never leak direct if proxy dies',
        ]
    lines += [
        'user_pref("network.dns.disableIPv6", true); // prevent IPv6 bypassing the proxy',
        "",
        "// WebRTC: hard off + belt-and-suspenders",
        'user_pref("media.peerconnection.enabled", false);',
        'user_pref("media.peerconnection.ice.default_address_only", true);',
        'user_pref("media.peerconnection.ice.no_host", true);',
        'user_pref("media.peerconnection.ice.proxy_only_if_behind_proxy", true);',
        "",
        "// NOTE: no privacy.resistFingerprinting here — Camoufox does its own",
        "// C++-level spoofing via the persona config; RFP would conflict with it.",
        "",
        "// hygiene",
        'user_pref("browser.shell.checkDefaultBrowser", false);',
        'user_pref("browser.shell.skipDefaultBrowserCheckOnFirstRun", true);',
        'user_pref("browser.aboutwelcome.enabled", false);',
        'user_pref("trailhead.firstrun.didSeeAboutWelcome", true);',
        'user_pref("datareporting.policy.dataSubmissionEnabled", false);',
        'user_pref("datareporting.healthreport.uploadEnabled", false);',
        'user_pref("app.shield.optoutstudies.enabled", false);',
        'user_pref("browser.discovery.enabled", false);',
        'user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);',
        'user_pref("signon.rememberSignons", false);',
        'user_pref("signon.autofillForms", false);',
        'user_pref("browser.formfill.enable", false);',
        'user_pref("browser.sessionstore.resume_from_crash", false);',
        'user_pref("toolkit.startup.max_resumed_crashes", -1); // never offer Troubleshoot Mode after a hard kill',
        'user_pref("browser.sessionstore.max_resumed_crashes", -1); // legacy name of the same pref',
        'user_pref("dom.security.https_only_mode", true);',
    ]
    (profile_dir / "user.js").write_text("\n".join(lines) + "\n")


def create_profiles(count, log=print):
    if not 1 <= count <= MAX_SESSIONS:
        raise ValueError(f"identity count must be 1-{MAX_SESSIONS} (got {count})")
    entries = proxy_entries()
    if not entries:
        raise RuntimeError(f"{CONF} has no proxy entries")
    if count > len(entries):
        log(f"warning: {len(entries)} proxies for {count} identities — egresses repeat (shared IPs link identities)")
    # clear any previous set so a smaller count doesn't leave stale profiles behind
    if PROFILES.is_dir() and PROFILES == ROOT / "profiles":
        shutil.rmtree(PROFILES)
    PROFILES.mkdir(parents=True, exist_ok=True)
    for i in range(count):
        ident = f"id{i + 1}"
        entry = entries[i % len(entries)]
        if entry == "DIRECT":
            log(f"warning: {ident} will connect DIRECTLY (your real IP)")
        profile_dir = PROFILES / ident
        profile_dir.mkdir(parents=True, exist_ok=True)
        write_user_js(profile_dir, i, entry)
    # one Camoufox persona per identity (does GeoIP lookups through the proxies)
    for line in generate_personas(count):
        log(line)
    log(f"Done. {count} profiles created.")


def load_persona_env(path):
    env = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line.startswith("export ") or "=" not in line:
            continue
        key, _, value = line[len("export "):].partition("=")
        parsed = shlex.split(value)
        env[key] = parsed[0] if parsed else ""
    return env


def existing_idents():
    if not PROFILES.is_dir():
        return []
    idents = [p.name for p in PROFILES.iterdir() if p.is_dir() and re.fullmatch(r"id\d+", p.name)]
    return sorted(idents, key=lambda name: int(name[2:]))


def launch_profiles(url="about:blank", log=print):
    ff = browser_path()
    idents = existing_idents()
    if not idents:
        raise RuntimeError("no profiles found — run create first")
    for ident in idents:
        profile_dir = PROFILES / ident
        if not (profile_dir / "user.js").is_file() or not (profile_dir / "persona.env").is_file():
            raise RuntimeError(f"{profile_dir} is incomplete — run create first")
        if LAUNCH_STAGGER > 0:
            time.sleep(random.randint(0, LAUNCH_STAGGER))
        env = os.environ.copy()
        env.update(load_persona_env(profile_dir / "persona.env"))
        proc = subprocess.Popen(
            [ff, "-no-remote", "-profile", str(profile_dir), "--new-window", url],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            env=env,
        )
        _tracked[ident] = {"popen": proc, "url": url, "started_at": time.time()}
        log(f"launched {ident} (pid {proc.pid})")
    log(f"All {len(idents)} identities running.")


def stop_profiles(log=print):
    running = {ident: t for ident, t in _tracked.items() if t["popen"].poll() is None}
    if running:
        for t in running.values():
            t["popen"].terminate()
        log(f"terminated {len(running)} instances, waiting for exit…")
        deadline = time.time() + 60
        while time.time() < deadline:
            if all(t["popen"].poll() is not None for t in running.values()):
                break
            time.sleep(0.5)
        for ident, t in running.items():
            if t["popen"].poll() is None:
                log(f"force-killing {ident} (pid {t['popen'].pid})")
                t["popen"].kill()
        time.sleep(1)
    else:
        log("no tracked instances running")
    _tracked.clear()
    # safety: only ever delete the profiles dir inside this project's folder
    if PROFILES.is_dir() and PROFILES == ROOT / "profiles":
        shutil.rmtree(PROFILES)
        log("profiles deleted — run create to start a fresh set")


def _persona_summary(profile_dir):
    persona = profile_dir / "persona.env"
    if not persona.is_file():
        return {}
    try:
        env = load_persona_env(persona)
        cfg = json.loads("".join(v for k, v in sorted(env.items()) if k.startswith("CAMOU_CONFIG_")))
    except (ValueError, OSError):
        return {}
    ua = cfg.get("navigator.userAgent", "")
    if "Windows" in ua:
        os_name = "windows"
    elif "Macintosh" in ua:
        os_name = "macos"
    elif "Linux" in ua:
        os_name = "linux"
    else:
        os_name = "?"
    return {
        "os": os_name,
        "ua_tail": ua[-40:],
        "tz": cfg.get("timezone", cfg.get("int:timezone", "?")),
    }


def status():
    entries = proxy_entries() if CONF.is_file() else []
    identities = []
    for ident in existing_idents():
        index = int(ident[2:])
        tracked = _tracked.get(ident)
        if tracked is not None:
            alive = tracked["popen"].poll() is None
            state = {"tracked": True, "running": alive, "pid": tracked["popen"].pid if alive else None}
        else:
            state = {"tracked": False, "running": None, "pid": None}
        identities.append(
            {
                "id": ident,
                "proxy": proxy_for(index, entries) if entries else "?",
                **_persona_summary(PROFILES / ident),
                **state,
            }
        )
    return {
        "proxy_entries": len(entries),
        "direct_entries": sum(1 for e in entries if e == "DIRECT"),
        "identities": identities,
    }
